# Generated by Django 5.0.3 on 2026-03-20 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Commodities',
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analytics.commodity')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['commodity', 'timestamp'], name='analytics_p_commodi_87536f_idx'), models.Index(fields=['timestamp'], name='analytics_p_timesta_9d48ff_idx')],
                'unique_together': {('commodity', 'timestamp')},
            },
        ),
    ]
