"""Add insights and alerts tables

Revision ID: 8fb2fe847288
Revises: bcc4b9121935
Create Date: 2026-05-11 13:44:09.401070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fb2fe847288'
down_revision: Union[str, None] = 'bcc4b9121935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo_alerta', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(length=80), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('nivel_severidad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_id'), 'alertas', ['id'], unique=False)
    op.create_index(op.f('ix_alertas_tipo_alerta'), 'alertas', ['tipo_alerta'], unique=False)
    op.create_table('resumenes_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_resumen', sa.Date(), nullable=True),
    sa.Column('titulo_jornada', sa.String(), nullable=True),
    sa.Column('resumen_oro', sa.Text(), nullable=True),
    sa.Column('resumen_petroleo', sa.Text(), nullable=True),
    sa.Column('leccion_concepto', sa.String(), nullable=True),
    sa.Column('leccion_explicacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_diarios_fecha_resumen'), 'resumenes_diarios', ['fecha_resumen'], unique=True)
    op.create_index(op.f('ix_resumenes_diarios_id'), 'resumenes_diarios', ['id'], unique=False)
    op.drop_index(op.f('market_ticks_timestamp_idx'), table_name='market_ticks')
    op.create_index(op.f('ix_market_ticks_timestamp'), 'market_ticks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_ticks_timestamp'), table_name='market_ticks')
    op.create_index(op.f('market_ticks_timestamp_idx'), 'market_ticks', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_resumenes_diarios_id'), table_name='resumenes_diarios')
    op.drop_index(op.f('ix_resumenes_diarios_fecha_resumen'), table_name='resumenes_diarios')
    op.drop_table('resumenes_diarios')
    op.drop_index(op.f('ix_alertas_tipo_alerta'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_id'), table_name='alertas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
